language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - echo $OPENSHIFT_MONGODB_DB_HOST
deploy:
 provider: openshift
 user: ruizdiazchristiand@gmail.com
 password: practicasch15
 domain: chrdtm
 app:
   master: vacacionespermanentes